swagger: "2.0"
info:
  version: "1.0.0"
  title: "bookshelf-web-api"
  description: "for bookshelf-web-api"
host: "localhost:8000"
basePath: "/api"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
tags:
- name: "books"
  description: "本"
- name: "accounts"
  description: "アカウント"
paths:
  /books:
    get:
      tags:
        - "books"
      summary: "本の一覧取得"
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Books'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - "books"
      summary: "本の新規登録"
      parameters:
        - name: id
          in: "path"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Book'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"          
  /books/{id}:
    get:
      tags:
        - "books"
      summary: "本の取得"
      parameters:
        - name: id
          in: "path"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Book'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    put:
      tags:
        - "books"
      summary: "本の編集"
      parameters:
        - name: id
          in: "path"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Book'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - "books"
      summary: "本の削除"
      parameters:
        - name: id
          in: "path"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/Book'
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
            
definitions:
  Book:
    type: object
    properties:
      id:
        type: number
        format: uint
      title:
        type: string
      readStatus:
        type: number
        format: uint
      categorys:
        type: array
        items:
          type: number
      charactors:
        type: array
        items:
          type: number
      prevBook:
        type: number
      nextBook:
        type: number
      description:
        type: string
      createdAt:
        type: "string"
        format: "date-time"
        description: "nullable"
      updatedAt:
        type: "string"
        format: "date-time"
        description: "nullable"
  Books:
    type: "object"
    properties:
      content:
        type: "array"
        items:
          $ref: "#/definitions/Book"
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
