// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"bookshelf-web-api/restapi/operations/book_description"
	"bookshelf-web-api/restapi/operations/books"
)

// NewBookshelfWebAPI creates a new BookshelfWeb instance
func NewBookshelfWebAPI(spec *loads.Document) *BookshelfWebAPI {
	return &BookshelfWebAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		BooksDeleteBooksIDHandler: books.DeleteBooksIDHandlerFunc(func(params books.DeleteBooksIDParams) middleware.Responder {
			return middleware.NotImplemented("operation BooksDeleteBooksID has not yet been implemented")
		}),
		BooksGetBooksHandler: books.GetBooksHandlerFunc(func(params books.GetBooksParams) middleware.Responder {
			return middleware.NotImplemented("operation BooksGetBooks has not yet been implemented")
		}),
		BooksGetBooksIDHandler: books.GetBooksIDHandlerFunc(func(params books.GetBooksIDParams) middleware.Responder {
			return middleware.NotImplemented("operation BooksGetBooksID has not yet been implemented")
		}),
		BookDescriptionGetBooksIDDescriptionHandler: book_description.GetBooksIDDescriptionHandlerFunc(func(params book_description.GetBooksIDDescriptionParams) middleware.Responder {
			return middleware.NotImplemented("operation BookDescriptionGetBooksIDDescription has not yet been implemented")
		}),
		BooksPostBooksHandler: books.PostBooksHandlerFunc(func(params books.PostBooksParams) middleware.Responder {
			return middleware.NotImplemented("operation BooksPostBooks has not yet been implemented")
		}),
		BookDescriptionPostBooksIDDescriptionHandler: book_description.PostBooksIDDescriptionHandlerFunc(func(params book_description.PostBooksIDDescriptionParams) middleware.Responder {
			return middleware.NotImplemented("operation BookDescriptionPostBooksIDDescription has not yet been implemented")
		}),
		BooksPutBooksIDHandler: books.PutBooksIDHandlerFunc(func(params books.PutBooksIDParams) middleware.Responder {
			return middleware.NotImplemented("operation BooksPutBooksID has not yet been implemented")
		}),
		BookDescriptionPutBooksIDDescriptionHandler: book_description.PutBooksIDDescriptionHandlerFunc(func(params book_description.PutBooksIDDescriptionParams) middleware.Responder {
			return middleware.NotImplemented("operation BookDescriptionPutBooksIDDescription has not yet been implemented")
		}),
	}
}

/*BookshelfWebAPI for bookshelf-web-api */
type BookshelfWebAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// BooksDeleteBooksIDHandler sets the operation handler for the delete books ID operation
	BooksDeleteBooksIDHandler books.DeleteBooksIDHandler
	// BooksGetBooksHandler sets the operation handler for the get books operation
	BooksGetBooksHandler books.GetBooksHandler
	// BooksGetBooksIDHandler sets the operation handler for the get books ID operation
	BooksGetBooksIDHandler books.GetBooksIDHandler
	// BookDescriptionGetBooksIDDescriptionHandler sets the operation handler for the get books ID description operation
	BookDescriptionGetBooksIDDescriptionHandler book_description.GetBooksIDDescriptionHandler
	// BooksPostBooksHandler sets the operation handler for the post books operation
	BooksPostBooksHandler books.PostBooksHandler
	// BookDescriptionPostBooksIDDescriptionHandler sets the operation handler for the post books ID description operation
	BookDescriptionPostBooksIDDescriptionHandler book_description.PostBooksIDDescriptionHandler
	// BooksPutBooksIDHandler sets the operation handler for the put books ID operation
	BooksPutBooksIDHandler books.PutBooksIDHandler
	// BookDescriptionPutBooksIDDescriptionHandler sets the operation handler for the put books ID description operation
	BookDescriptionPutBooksIDDescriptionHandler book_description.PutBooksIDDescriptionHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *BookshelfWebAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *BookshelfWebAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *BookshelfWebAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *BookshelfWebAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *BookshelfWebAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *BookshelfWebAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *BookshelfWebAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the BookshelfWebAPI
func (o *BookshelfWebAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BooksDeleteBooksIDHandler == nil {
		unregistered = append(unregistered, "books.DeleteBooksIDHandler")
	}

	if o.BooksGetBooksHandler == nil {
		unregistered = append(unregistered, "books.GetBooksHandler")
	}

	if o.BooksGetBooksIDHandler == nil {
		unregistered = append(unregistered, "books.GetBooksIDHandler")
	}

	if o.BookDescriptionGetBooksIDDescriptionHandler == nil {
		unregistered = append(unregistered, "book_description.GetBooksIDDescriptionHandler")
	}

	if o.BooksPostBooksHandler == nil {
		unregistered = append(unregistered, "books.PostBooksHandler")
	}

	if o.BookDescriptionPostBooksIDDescriptionHandler == nil {
		unregistered = append(unregistered, "book_description.PostBooksIDDescriptionHandler")
	}

	if o.BooksPutBooksIDHandler == nil {
		unregistered = append(unregistered, "books.PutBooksIDHandler")
	}

	if o.BookDescriptionPutBooksIDDescriptionHandler == nil {
		unregistered = append(unregistered, "book_description.PutBooksIDDescriptionHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *BookshelfWebAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *BookshelfWebAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *BookshelfWebAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *BookshelfWebAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *BookshelfWebAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *BookshelfWebAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the bookshelf web API
func (o *BookshelfWebAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *BookshelfWebAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/books/{id}"] = books.NewDeleteBooksID(o.context, o.BooksDeleteBooksIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/books"] = books.NewGetBooks(o.context, o.BooksGetBooksHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/books/{id}"] = books.NewGetBooksID(o.context, o.BooksGetBooksIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/books/{id}/description"] = book_description.NewGetBooksIDDescription(o.context, o.BookDescriptionGetBooksIDDescriptionHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/books"] = books.NewPostBooks(o.context, o.BooksPostBooksHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/books/{id}/description"] = book_description.NewPostBooksIDDescription(o.context, o.BookDescriptionPostBooksIDDescriptionHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/books/{id}"] = books.NewPutBooksID(o.context, o.BooksPutBooksIDHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/books/{id}/description"] = book_description.NewPutBooksIDDescription(o.context, o.BookDescriptionPutBooksIDDescriptionHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *BookshelfWebAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *BookshelfWebAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *BookshelfWebAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *BookshelfWebAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
