// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi bookshelf-web-api
for bookshelf-web-api


    Schemes:
      http
    Host: localhost:8000
    BasePath: /api
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
