// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "for bookshelf-web-api",
    "title": "bookshelf-web-api",
    "version": "1.0.0"
  },
  "host": "localhost:8000",
  "basePath": "/api",
  "paths": {
    "/books": {
      "get": {
        "tags": [
          "books"
        ],
        "summary": "本の一覧取得",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/BooksResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "books"
        ],
        "summary": "本の新規登録",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BookRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/BookResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/books/{id}": {
      "get": {
        "tags": [
          "books"
        ],
        "summary": "本の取得",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/BookResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "books"
        ],
        "summary": "本の編集",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BookRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Book"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "books"
        ],
        "summary": "本の削除",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/OkResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/books/{id}/description": {
      "get": {
        "tags": [
          "book description"
        ],
        "summary": "本のディスクリプション取得",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/BookDescriptionResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "book description"
        ],
        "summary": "本のディスクリプションを編集",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BookDescriptionRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/BookDescriptionResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "book description"
        ],
        "summary": "本のディスクリプション登録",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BookDescriptionRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/BookDescriptionResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Book": {
      "type": "object",
      "properties": {
        "author": {
          "type": "string"
        },
        "categorys": {
          "type": "array",
          "items": {
            "type": "number"
          }
        },
        "createdAt": {
          "description": "nullable",
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "number",
          "format": "int64"
        },
        "nextBookId": {
          "type": "number",
          "format": "int64"
        },
        "prevBookId": {
          "type": "number",
          "format": "int64"
        },
        "readStatus": {
          "type": "number",
          "format": "int32"
        },
        "title": {
          "type": "string"
        },
        "updatedAt": {
          "description": "nullable",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "BookDescription": {
      "type": "object",
      "properties": {
        "bookId": {
          "type": "number",
          "format": "int64"
        },
        "createdAt": {
          "description": "nullable",
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "number",
          "format": "int64"
        },
        "updatedAt": {
          "description": "nullable",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "BookDescriptionRequest": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        }
      }
    },
    "BookDescriptionResponse": {
      "type": "object",
      "properties": {
        "contents": {
          "$ref": "#/definitions/BookDescription"
        },
        "message": {
          "type": "string",
          "example": "ok"
        },
        "resultCode": {
          "type": "number",
          "format": "int32",
          "example": 1
        }
      }
    },
    "BookDescriptions": {
      "type": "object",
      "properties": {
        "content": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BookDescription"
          }
        }
      }
    },
    "BookDescriptionsResponse": {
      "type": "object",
      "properties": {
        "contents": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BookDescriptionsResponse"
          }
        },
        "message": {
          "type": "string",
          "example": "ok"
        },
        "resultCode": {
          "type": "number",
          "format": "int32",
          "example": 1
        }
      }
    },
    "BookRequest": {
      "type": "object",
      "properties": {
        "author": {
          "type": "string"
        },
        "categorys": {
          "type": "array",
          "items": {
            "type": "number"
          }
        },
        "createdAt": {
          "description": "nullable",
          "type": "string",
          "format": "date-time"
        },
        "nextBookId": {
          "type": "number",
          "format": "int64"
        },
        "prevBookId": {
          "type": "number",
          "format": "int64"
        },
        "title": {
          "type": "string"
        },
        "updatedAt": {
          "description": "nullable",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "BookResponse": {
      "type": "object",
      "properties": {
        "contents": {
          "$ref": "#/definitions/Book"
        },
        "message": {
          "type": "string",
          "example": "ok"
        },
        "resultCode": {
          "type": "number",
          "format": "int32",
          "example": 1
        }
      }
    },
    "Books": {
      "type": "object",
      "properties": {
        "content": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Book"
          }
        }
      }
    },
    "BooksResponse": {
      "type": "object",
      "properties": {
        "contents": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Books"
          }
        },
        "message": {
          "type": "string",
          "example": "ok"
        },
        "resultCode": {
          "type": "number",
          "format": "int32",
          "example": 1
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "OkResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "example": "ok"
        },
        "resultCode": {
          "type": "number",
          "format": "int32",
          "example": 1
        }
      }
    }
  },
  "tags": [
    {
      "description": "本",
      "name": "books"
    },
    {
      "description": "本のメモ",
      "name": "book description"
    },
    {
      "description": "アカウント",
      "name": "accounts"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "for bookshelf-web-api",
    "title": "bookshelf-web-api",
    "version": "1.0.0"
  },
  "host": "localhost:8000",
  "basePath": "/api",
  "paths": {
    "/books": {
      "get": {
        "tags": [
          "books"
        ],
        "summary": "本の一覧取得",
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/BooksResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "books"
        ],
        "summary": "本の新規登録",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BookRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/BookResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/books/{id}": {
      "get": {
        "tags": [
          "books"
        ],
        "summary": "本の取得",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/BookResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "books"
        ],
        "summary": "本の編集",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BookRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/Book"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "books"
        ],
        "summary": "本の削除",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/OkResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/books/{id}/description": {
      "get": {
        "tags": [
          "book description"
        ],
        "summary": "本のディスクリプション取得",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/BookDescriptionResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "put": {
        "tags": [
          "book description"
        ],
        "summary": "本のディスクリプションを編集",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BookDescriptionRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/BookDescriptionResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "book description"
        ],
        "summary": "本のディスクリプション登録",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/BookDescriptionRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/BookDescriptionResponse"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Book": {
      "type": "object",
      "properties": {
        "author": {
          "type": "string"
        },
        "categorys": {
          "type": "array",
          "items": {
            "type": "number"
          }
        },
        "createdAt": {
          "description": "nullable",
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "number",
          "format": "int64"
        },
        "nextBookId": {
          "type": "number",
          "format": "int64"
        },
        "prevBookId": {
          "type": "number",
          "format": "int64"
        },
        "readStatus": {
          "type": "number",
          "format": "int32"
        },
        "title": {
          "type": "string"
        },
        "updatedAt": {
          "description": "nullable",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "BookDescription": {
      "type": "object",
      "properties": {
        "bookId": {
          "type": "number",
          "format": "int64"
        },
        "createdAt": {
          "description": "nullable",
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "number",
          "format": "int64"
        },
        "updatedAt": {
          "description": "nullable",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "BookDescriptionRequest": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        }
      }
    },
    "BookDescriptionResponse": {
      "type": "object",
      "properties": {
        "contents": {
          "$ref": "#/definitions/BookDescription"
        },
        "message": {
          "type": "string",
          "example": "ok"
        },
        "resultCode": {
          "type": "number",
          "format": "int32",
          "example": 1
        }
      }
    },
    "BookDescriptions": {
      "type": "object",
      "properties": {
        "content": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BookDescription"
          }
        }
      }
    },
    "BookDescriptionsResponse": {
      "type": "object",
      "properties": {
        "contents": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BookDescriptionsResponse"
          }
        },
        "message": {
          "type": "string",
          "example": "ok"
        },
        "resultCode": {
          "type": "number",
          "format": "int32",
          "example": 1
        }
      }
    },
    "BookRequest": {
      "type": "object",
      "properties": {
        "author": {
          "type": "string"
        },
        "categorys": {
          "type": "array",
          "items": {
            "type": "number"
          }
        },
        "createdAt": {
          "description": "nullable",
          "type": "string",
          "format": "date-time"
        },
        "nextBookId": {
          "type": "number",
          "format": "int64"
        },
        "prevBookId": {
          "type": "number",
          "format": "int64"
        },
        "title": {
          "type": "string"
        },
        "updatedAt": {
          "description": "nullable",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "BookResponse": {
      "type": "object",
      "properties": {
        "contents": {
          "$ref": "#/definitions/Book"
        },
        "message": {
          "type": "string",
          "example": "ok"
        },
        "resultCode": {
          "type": "number",
          "format": "int32",
          "example": 1
        }
      }
    },
    "Books": {
      "type": "object",
      "properties": {
        "content": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Book"
          }
        }
      }
    },
    "BooksResponse": {
      "type": "object",
      "properties": {
        "contents": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Books"
          }
        },
        "message": {
          "type": "string",
          "example": "ok"
        },
        "resultCode": {
          "type": "number",
          "format": "int32",
          "example": 1
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "OkResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "example": "ok"
        },
        "resultCode": {
          "type": "number",
          "format": "int32",
          "example": 1
        }
      }
    }
  },
  "tags": [
    {
      "description": "本",
      "name": "books"
    },
    {
      "description": "本のメモ",
      "name": "book description"
    },
    {
      "description": "アカウント",
      "name": "accounts"
    }
  ]
}`))
}
