// Code generated by go-swagger; DO NOT EDIT.

package book_description

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "bookshelf-web-api/models"
)

// GetBooksIDDescriptionOKCode is the HTTP code returned for type GetBooksIDDescriptionOK
const GetBooksIDDescriptionOKCode int = 200

/*GetBooksIDDescriptionOK Success

swagger:response getBooksIdDescriptionOK
*/
type GetBooksIDDescriptionOK struct {

	/*
	  In: Body
	*/
	Payload *models.BookDescriptionResponse `json:"body,omitempty"`
}

// NewGetBooksIDDescriptionOK creates GetBooksIDDescriptionOK with default headers values
func NewGetBooksIDDescriptionOK() *GetBooksIDDescriptionOK {

	return &GetBooksIDDescriptionOK{}
}

// WithPayload adds the payload to the get books Id description o k response
func (o *GetBooksIDDescriptionOK) WithPayload(payload *models.BookDescriptionResponse) *GetBooksIDDescriptionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books Id description o k response
func (o *GetBooksIDDescriptionOK) SetPayload(payload *models.BookDescriptionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksIDDescriptionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetBooksIDDescriptionDefault generic error response

swagger:response getBooksIdDescriptionDefault
*/
type GetBooksIDDescriptionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBooksIDDescriptionDefault creates GetBooksIDDescriptionDefault with default headers values
func NewGetBooksIDDescriptionDefault(code int) *GetBooksIDDescriptionDefault {
	if code <= 0 {
		code = 500
	}

	return &GetBooksIDDescriptionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get books ID description default response
func (o *GetBooksIDDescriptionDefault) WithStatusCode(code int) *GetBooksIDDescriptionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get books ID description default response
func (o *GetBooksIDDescriptionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get books ID description default response
func (o *GetBooksIDDescriptionDefault) WithPayload(payload *models.Error) *GetBooksIDDescriptionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books ID description default response
func (o *GetBooksIDDescriptionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksIDDescriptionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
