// Code generated by go-swagger; DO NOT EDIT.

package book_description

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "bookshelf-web-api/models"
)

// PostBooksIDDescriptionOKCode is the HTTP code returned for type PostBooksIDDescriptionOK
const PostBooksIDDescriptionOKCode int = 200

/*PostBooksIDDescriptionOK Success

swagger:response postBooksIdDescriptionOK
*/
type PostBooksIDDescriptionOK struct {

	/*
	  In: Body
	*/
	Payload *models.BookDescriptionResponse `json:"body,omitempty"`
}

// NewPostBooksIDDescriptionOK creates PostBooksIDDescriptionOK with default headers values
func NewPostBooksIDDescriptionOK() *PostBooksIDDescriptionOK {

	return &PostBooksIDDescriptionOK{}
}

// WithPayload adds the payload to the post books Id description o k response
func (o *PostBooksIDDescriptionOK) WithPayload(payload *models.BookDescriptionResponse) *PostBooksIDDescriptionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post books Id description o k response
func (o *PostBooksIDDescriptionOK) SetPayload(payload *models.BookDescriptionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBooksIDDescriptionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostBooksIDDescriptionDefault generic error response

swagger:response postBooksIdDescriptionDefault
*/
type PostBooksIDDescriptionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostBooksIDDescriptionDefault creates PostBooksIDDescriptionDefault with default headers values
func NewPostBooksIDDescriptionDefault(code int) *PostBooksIDDescriptionDefault {
	if code <= 0 {
		code = 500
	}

	return &PostBooksIDDescriptionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post books ID description default response
func (o *PostBooksIDDescriptionDefault) WithStatusCode(code int) *PostBooksIDDescriptionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post books ID description default response
func (o *PostBooksIDDescriptionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post books ID description default response
func (o *PostBooksIDDescriptionDefault) WithPayload(payload *models.Error) *PostBooksIDDescriptionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post books ID description default response
func (o *PostBooksIDDescriptionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBooksIDDescriptionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
