// Code generated by go-swagger; DO NOT EDIT.

package book_description

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostBooksIDDescriptionHandlerFunc turns a function with the right signature into a post books ID description handler
type PostBooksIDDescriptionHandlerFunc func(PostBooksIDDescriptionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostBooksIDDescriptionHandlerFunc) Handle(params PostBooksIDDescriptionParams) middleware.Responder {
	return fn(params)
}

// PostBooksIDDescriptionHandler interface for that can handle valid post books ID description params
type PostBooksIDDescriptionHandler interface {
	Handle(PostBooksIDDescriptionParams) middleware.Responder
}

// NewPostBooksIDDescription creates a new http.Handler for the post books ID description operation
func NewPostBooksIDDescription(ctx *middleware.Context, handler PostBooksIDDescriptionHandler) *PostBooksIDDescription {
	return &PostBooksIDDescription{Context: ctx, Handler: handler}
}

/*PostBooksIDDescription swagger:route POST /books/{id}/description book description postBooksIdDescription

本のディスクリプション登録

*/
type PostBooksIDDescription struct {
	Context *middleware.Context
	Handler PostBooksIDDescriptionHandler
}

func (o *PostBooksIDDescription) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostBooksIDDescriptionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
