// Code generated by go-swagger; DO NOT EDIT.

package book_description

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "bookshelf-web-api/models"
)

// PutBooksIDDescriptionOKCode is the HTTP code returned for type PutBooksIDDescriptionOK
const PutBooksIDDescriptionOKCode int = 200

/*PutBooksIDDescriptionOK Success

swagger:response putBooksIdDescriptionOK
*/
type PutBooksIDDescriptionOK struct {

	/*
	  In: Body
	*/
	Payload *models.BookDescriptionResponse `json:"body,omitempty"`
}

// NewPutBooksIDDescriptionOK creates PutBooksIDDescriptionOK with default headers values
func NewPutBooksIDDescriptionOK() *PutBooksIDDescriptionOK {

	return &PutBooksIDDescriptionOK{}
}

// WithPayload adds the payload to the put books Id description o k response
func (o *PutBooksIDDescriptionOK) WithPayload(payload *models.BookDescriptionResponse) *PutBooksIDDescriptionOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put books Id description o k response
func (o *PutBooksIDDescriptionOK) SetPayload(payload *models.BookDescriptionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutBooksIDDescriptionOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutBooksIDDescriptionDefault generic error response

swagger:response putBooksIdDescriptionDefault
*/
type PutBooksIDDescriptionDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutBooksIDDescriptionDefault creates PutBooksIDDescriptionDefault with default headers values
func NewPutBooksIDDescriptionDefault(code int) *PutBooksIDDescriptionDefault {
	if code <= 0 {
		code = 500
	}

	return &PutBooksIDDescriptionDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put books ID description default response
func (o *PutBooksIDDescriptionDefault) WithStatusCode(code int) *PutBooksIDDescriptionDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put books ID description default response
func (o *PutBooksIDDescriptionDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put books ID description default response
func (o *PutBooksIDDescriptionDefault) WithPayload(payload *models.Error) *PutBooksIDDescriptionDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put books ID description default response
func (o *PutBooksIDDescriptionDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutBooksIDDescriptionDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
