// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "bookshelf-web-api/models"
)

// DeleteBooksIDOKCode is the HTTP code returned for type DeleteBooksIDOK
const DeleteBooksIDOKCode int = 200

/*DeleteBooksIDOK Success

swagger:response deleteBooksIdOK
*/
type DeleteBooksIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.OkResponse `json:"body,omitempty"`
}

// NewDeleteBooksIDOK creates DeleteBooksIDOK with default headers values
func NewDeleteBooksIDOK() *DeleteBooksIDOK {

	return &DeleteBooksIDOK{}
}

// WithPayload adds the payload to the delete books Id o k response
func (o *DeleteBooksIDOK) WithPayload(payload *models.OkResponse) *DeleteBooksIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete books Id o k response
func (o *DeleteBooksIDOK) SetPayload(payload *models.OkResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBooksIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteBooksIDDefault generic error response

swagger:response deleteBooksIdDefault
*/
type DeleteBooksIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteBooksIDDefault creates DeleteBooksIDDefault with default headers values
func NewDeleteBooksIDDefault(code int) *DeleteBooksIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteBooksIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete books ID default response
func (o *DeleteBooksIDDefault) WithStatusCode(code int) *DeleteBooksIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete books ID default response
func (o *DeleteBooksIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete books ID default response
func (o *DeleteBooksIDDefault) WithPayload(payload *models.Error) *DeleteBooksIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete books ID default response
func (o *DeleteBooksIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBooksIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
