// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "bookshelf-web-api/models"
)

// GetBooksIDOKCode is the HTTP code returned for type GetBooksIDOK
const GetBooksIDOKCode int = 200

/*GetBooksIDOK Success

swagger:response getBooksIdOK
*/
type GetBooksIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.BookResponse `json:"body,omitempty"`
}

// NewGetBooksIDOK creates GetBooksIDOK with default headers values
func NewGetBooksIDOK() *GetBooksIDOK {

	return &GetBooksIDOK{}
}

// WithPayload adds the payload to the get books Id o k response
func (o *GetBooksIDOK) WithPayload(payload *models.BookResponse) *GetBooksIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books Id o k response
func (o *GetBooksIDOK) SetPayload(payload *models.BookResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetBooksIDDefault generic error response

swagger:response getBooksIdDefault
*/
type GetBooksIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBooksIDDefault creates GetBooksIDDefault with default headers values
func NewGetBooksIDDefault(code int) *GetBooksIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetBooksIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get books ID default response
func (o *GetBooksIDDefault) WithStatusCode(code int) *GetBooksIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get books ID default response
func (o *GetBooksIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get books ID default response
func (o *GetBooksIDDefault) WithPayload(payload *models.Error) *GetBooksIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books ID default response
func (o *GetBooksIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
