// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "bookshelf-web-api/models"
)

// PutBooksIDOKCode is the HTTP code returned for type PutBooksIDOK
const PutBooksIDOKCode int = 200

/*PutBooksIDOK Success

swagger:response putBooksIdOK
*/
type PutBooksIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewPutBooksIDOK creates PutBooksIDOK with default headers values
func NewPutBooksIDOK() *PutBooksIDOK {

	return &PutBooksIDOK{}
}

// WithPayload adds the payload to the put books Id o k response
func (o *PutBooksIDOK) WithPayload(payload *models.Book) *PutBooksIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put books Id o k response
func (o *PutBooksIDOK) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutBooksIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutBooksIDDefault generic error response

swagger:response putBooksIdDefault
*/
type PutBooksIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutBooksIDDefault creates PutBooksIDDefault with default headers values
func NewPutBooksIDDefault(code int) *PutBooksIDDefault {
	if code <= 0 {
		code = 500
	}

	return &PutBooksIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put books ID default response
func (o *PutBooksIDDefault) WithStatusCode(code int) *PutBooksIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put books ID default response
func (o *PutBooksIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put books ID default response
func (o *PutBooksIDDefault) WithPayload(payload *models.Error) *PutBooksIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put books ID default response
func (o *PutBooksIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutBooksIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
