// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// BooksResponse books response
// swagger:model BooksResponse
type BooksResponse struct {

	// contents
	Contents []*Books `json:"contents"`

	// message
	Message string `json:"message,omitempty"`

	// result code
	ResultCode int32 `json:"resultCode,omitempty"`
}

// Validate validates this books response
func (m *BooksResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContents(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BooksResponse) validateContents(formats strfmt.Registry) error {

	if swag.IsZero(m.Contents) { // not required
		return nil
	}

	for i := 0; i < len(m.Contents); i++ {
		if swag.IsZero(m.Contents[i]) { // not required
			continue
		}

		if m.Contents[i] != nil {
			if err := m.Contents[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("contents" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *BooksResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BooksResponse) UnmarshalBinary(b []byte) error {
	var res BooksResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
