// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// BookDescriptionResponse book description response
// swagger:model BookDescriptionResponse
type BookDescriptionResponse struct {

	// contents
	Contents *BookDescription `json:"contents,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// result code
	ResultCode int32 `json:"resultCode,omitempty"`
}

// Validate validates this book description response
func (m *BookDescriptionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContents(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BookDescriptionResponse) validateContents(formats strfmt.Registry) error {

	if swag.IsZero(m.Contents) { // not required
		return nil
	}

	if m.Contents != nil {
		if err := m.Contents.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("contents")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BookDescriptionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BookDescriptionResponse) UnmarshalBinary(b []byte) error {
	var res BookDescriptionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
